from .genetic_encoders import AdditiveEncoder
from .genetic_encoders import AdditiveAlternateEncoder
from .genetic_encoders import DominantEncoder
from .genetic_encoders import RecessiveEncoder
from .genetic_encoders import HeterozygoteAdvantageEncoder
from .genetic_encoders import HeterozygoteDisadvantageEncoder
