#rom .genetic_encoders import AdditiveEncoder
#from .genetic_encoders import AdditiveAlternateEncoder
from .genetic_encoders import DominantEncoder
from .genetic_encoders import RecessiveEncoder
from .genetic_encoders import HeterosisEncoder
#from .genetic_encoders import HeterozygoteDisadvantageEncoder
#from .genetic_encoders import InverseEncoder
from .genetic_encoders import UnderDominanceEncoder
#from .genetic_encoders import UnderDominanceAlternateEncoder
from. genetic_encoders import OverDominanceEncoder
#from .genetic_encoders import OverDominanceAlternateEncoder
#from .genetic_encoders import OverDominancePlusEncoder
#from .genetic_encoders import OverDominancePlusAlternateEncoder
#from .genetic_encoders import TimesTwoEncoder
